# Generated by Django 3.2.25 on 2025-01-05 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_auto_20250105_1542'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='has_colors',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
